=== morepork/pacdefence/PacDefence/gui/maps/map.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--  This file is part of Pac Defence.
      
      Pac Defence is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
      
      Pac Defence is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
      
      You should have received a copy of the GNU General Public License
      along with Pac Defence.  If not, see <http://www.gnu.org/licenses/>.
      
      (C) Liam Byrne, 2008 - 09.
  -->
  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:element name="map">
      <xs:complexType>
         <xs:all>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="image" type="xs:string"/>
            <xs:element ref="pathPoints"/>
            <xs:element ref="path"/>
            <xs:element ref="pathBounds"/>
         </xs:all>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="pathPoints">
      <xs:complexType>
         <xs:sequence>
            <!--  Must have at least a first and last point -->
            <xs:element ref="point" maxOccurs="unbounded" minOccurs="2"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   <!-- The polygons listed here should cover the path exactly, they are used
        to figure out where towers and ghosts can be placed. -->
   <xs:element name="path">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="polygon" maxOccurs="unbounded" minOccurs="1"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   <!-- The shapes in here should cover the entire path, and should also be
        kept as small as possible for performance. For the same reason, only
        polygons that don't have too many points should be in here, otherwise
        use a bounding rectangle, or the like. -->
   <xs:element name="pathBounds">
      <xs:complexType>
         <xs:sequence>
            <xs:group ref="shape" maxOccurs="unbounded" minOccurs="1"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   <xs:group name="shape">
      <xs:choice>
         <xs:element ref="polygon"/>
         <xs:element ref="rectangle"/>
      </xs:choice>
   </xs:group>
   
   <xs:element name="polygon">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="point" maxOccurs="unbounded" minOccurs="3"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="rectangle">
      <xs:complexType>
         <xs:attribute name="x" type="xs:nonNegativeInteger"/>
         <xs:attribute name="y" type="xs:nonNegativeInteger"/>
         <xs:attribute name="width" type="xs:positiveInteger"/>
         <xs:attribute name="height" type="xs:positiveInteger"/>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="point">
      <xs:complexType>
         <xs:attribute name="x" type="xs:nonNegativeInteger"/>
         <xs:attribute name="y" type="xs:nonNegativeInteger"/>
      </xs:complexType>
   </xs:element>
    
</xs:schema>

=== morepork/pacdefence/PacDefence/gui/maps/curvyEasy.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="map.xsd">
	<description>Curvy Easy</description>
	<images>
		<image>curvyEasy.jpg</image>
	</images>
	<pathPoints>
		<point x="0" y="298" />
		<point x="236" y="296" />
		<point x="267" y="295" />
		<point x="289" y="290" />
		<point x="304" y="284" />
		<point x="316" y="275" />
		<point x="323" y="263" />
		<point x="327" y="248" />
		<point x="327" y="229" />
		<point x="325" y="208" />
		<point x="317" y="190" />
		<point x="304" y="182" />
		<point x="289" y="179" />
		<point x="275" y="187" />
		<point x="268" y="204" />
		<point x="266" y="223" />
		<point x="267" y="247" />
		<point x="280" y="273" />
		<point x="306" y="301" />
		<point x="323" y="325" />
		<point x="328" y="340" />
		<point x="330" y="356" />
		<point x="326" y="375" />
		<point x="316" y="390" />
		<point x="305" y="394" />
		<point x="290" y="396" />
		<point x="278" y="392" />
		<point x="269" y="380" />
		<point x="263" y="358" />
		<point x="264" y="343" />
		<point x="269" y="328" />
		<point x="278" y="315" />
		<point x="300" y="303" />
		<point x="343" y="296" />
		<point x="599" y="292" />
	</pathPoints>
	<path>
		<polygon>
			<point x="0" y="264" />
			<point x="236" y="265" />
			<point x="231" y="236" />
			<point x="230" y="200" />
			<point x="240" y="174" />
			<point x="250" y="161" />
			<point x="260" y="153" />
			<point x="270" y="148" />
			<point x="280" y="145" />
			<point x="290" y="143" />
			<point x="300" y="144" />
			<point x="310" y="145" />
			<point x="320" y="149" />
			<point x="330" y="154" />
			<point x="340" y="162" />
			<point x="350" y="175" />
			<point x="360" y="200" />
			<point x="363" y="233" />
			<point x="362" y="261" />
			<point x="399" y="260" />
			<point x="599" y="259" />
			<point x="599" y="322" />
			<point x="369" y="327" />
			<point x="362" y="329" />
			<point x="364" y="358" />
			<point x="359" y="380" />
			<point x="349" y="401" />
			<point x="339" y="413" />
			<point x="329" y="420" />
			<point x="319" y="424" />
			<point x="309" y="426" />
			<point x="299" y="427" />
			<point x="289" y="426" />
			<point x="279" y="423" />
			<point x="269" y="419" />
			<point x="259" y="413" />
			<point x="249" y="403" />
			<point x="239" y="388" />
			<point x="231" y="358" />
			<point x="231" y="325" />
			<point x="179" y="326" />
			<point x="0" y="326" />
		</polygon>
	</path>
	<pathBounds>
		<polygon>
			<point x="0" y="264" />
			<point x="236" y="265" />
			<point x="230" y="200" />
			<point x="240" y="174" />
			<point x="270" y="148" />
			<point x="300" y="144" />
			<point x="330" y="154" />
			<point x="350" y="175" />
			<point x="360" y="200" />
			<point x="363" y="233" />
			<point x="362" y="261" />
			<point x="599" y="259" />
			<point x="599" y="322" />
			<point x="362" y="329" />
			<point x="359" y="380" />
			<point x="339" y="413" />
			<point x="319" y="424" />
			<point x="279" y="423" />
			<point x="259" y="413" />
			<point x="249" y="403" />
			<point x="239" y="388" />
			<point x="231" y="325" />
			<point x="0" y="326" />
		</polygon>
	</pathBounds>
</map>

=== morepork/pacdefence/PacDefence/gui/maps/mosaicPathHard.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  This file is part of Pac Defence.
      
      Pac Defence is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
      
      Pac Defence is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
      
      You should have received a copy of the GNU General Public License
      along with Pac Defence.  If not, see <http://www.gnu.org/licenses/>.
      
      (C) Liam Byrne, 2008 - 09.
  -->
  
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
  <description>Hard</description>
  <image>mosaicPathHard.jpg</image>
  <pathPoints>
    <point x="0" y="230"/>
    <point x="300" y="230"/>
    <point x="300" y="370"/>
    <point x="600" y="370"/>
  </pathPoints>  
  <path>
    <polygon>
      <point x="0" y="200"/>
      <point x="326" y="200"/>
      <point x="326" y="340"/>
      <point x="600" y="340"/>
      <point x="600" y="400"/>
      <point x="272" y="400"/>
      <point x="272" y="260"/>
      <point x="0" y="260"/>
    </polygon>
  </path>
  <pathBounds>
    <polygon>
      <!-- Should be the same as the one above, don't know a nice way of reusing it -->
      <point x="0" y="200"/>
      <point x="326" y="200"/>
      <point x="326" y="340"/>
      <point x="600" y="340"/>
      <point x="600" y="400"/>
      <point x="272" y="400"/>
      <point x="272" y="260"/>
      <point x="0" y="260"/>
    </polygon>
  </pathBounds>
</map>

=== morepork/pacdefence/gui/maps/mosaicPathEasy.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  This file is part of Pac Defence.
      
      Pac Defence is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
      
      Pac Defence is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
      
      You should have received a copy of the GNU General Public License
      along with Pac Defence.  If not, see <http://www.gnu.org/licenses/>.
      
      (C) Liam Byrne, 2008 - 2012.
  -->
  
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
  <description>Mosaic Easy</description>
  <images>
    <image>mosaicPathEasy.jpg</image>
  </images>
  <pathPoints>
    <point x="0" y="130"/>
    <point x="420" y="130"/>
    <point x="420" y="470"/>
    <point x="135" y="470"/>
    <point x="135" y="280"/>
    <point x="600" y="280"/>
  </pathPoints>  
  <path>
    <!-- This is tricky as any inner part of a polygon's outline must be
         contained inside another polygon, otherwise creating a ghost fails -->
    <polygon>
      <point x="0" y="100"/>
      <point x="450" y="100"/>
      <point x="450" y="500"/>
      <point x="103" y="500"/>
      <point x="103" y="252"/>
      <point x="600" y="252"/>
      <point x="600" y="310"/>
      <point x="160" y="310"/>
      <point x="160" y="441"/>
      <point x="392" y="441"/>
      <point x="392" y="158"/>
      <point x="0" y="158"/>
    </polygon>
    <polygon>
      <point x="103" y="252"/>
      <point x="103" y="310"/>
      <point x="600" y="310"/>
      <point x="600" y="252"/>
    </polygon>
    <polygon>
      <point x="392" y="100"/>
      <point x="392" y="500"/>
      <point x="450" y="500"/>
      <point x="450" y="100"/>
    </polygon>
  </path>
  <pathBounds>
    <!-- Should be the same as the first one above, don't know a nice way of reusing it -->
    <polygon>
      <point x="0" y="100"/>
      <point x="450" y="100"/>
      <point x="450" y="500"/>
      <point x="103" y="500"/>
      <point x="103" y="252"/>
      <point x="600" y="252"/>
      <point x="600" y="310"/>
      <point x="160" y="310"/>
      <point x="160" y="441"/>
      <point x="392" y="441"/>
      <point x="392" y="158"/>
      <point x="0" y="158"/>
    </polygon>
    <rectangle x="392" y="252" width="58" height="58"/>
  </pathBounds>
</map>

=== morepork/pacdefence/PacDefence/gui/maps/mosaicPathMedium.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  This file is part of Pac Defence.
      
      Pac Defence is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
      
      Pac Defence is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
      
      You should have received a copy of the GNU General Public License
      along with Pac Defence.  If not, see <http://www.gnu.org/licenses/>.
      
      (C) Liam Byrne, 2008 - 09.
  -->
  
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
  <description>Mosaic Medium</description>
  <images>
    <image>mosaicPathMedium.jpg</image>
  </images>
  <pathPoints>
    <point x="0" y="135"/>
    <point x="235" y="135"/>
    <point x="235" y="335"/>
    <point x="100" y="335"/>
    <point x="100" y="470"/>
    <point x="600" y="470"/>
  </pathPoints>  
  <path>
    <polygon>
      <point x="0" y="106"/>
      <point x="273" y="106"/>
      <point x="273" y="372"/>
      <point x="137" y="372"/>
      <point x="137" y="438"/>
      <point x="600" y="438"/>
      <point x="600" y="503"/>
      <point x="67" y="503"/>
      <point x="67" y="305"/>
      <point x="203" y="305"/>
      <point x="203" y="166"/>
      <point x="0" y="166"/>
    </polygon>
  </path>
  <pathBounds>
    <polygon>
      <!-- Should be the same as the one above, don't know a nice way of reusing it -->
      <point x="0" y="106"/>
      <point x="273" y="106"/>
      <point x="273" y="372"/>
      <point x="137" y="372"/>
      <point x="137" y="438"/>
      <point x="600" y="438"/>
      <point x="600" y="503"/>
      <point x="67" y="503"/>
      <point x="67" y="305"/>
      <point x="203" y="305"/>
      <point x="203" y="166"/>
      <point x="0" y="166"/>
    </polygon>
  </pathBounds>
</map>
